### ISSUE TITLE
Multiple operation is not working

### ISSUE THREAD

**Issue by sshettyintacct** [Intacct/intacct-ws-test-tool#14]
<request>
  <control>
    <senderid>intacct_dev</senderid>
    <password>REMOVED_FOR_SECURITY_PURPOSES</password>
    <controlid>testRequestId</controlid>
    <uniqueid>false</uniqueid>
    <dtdversion>2.1</dtdversion>
    <includewhitespace>false</includewhitespace>
  </control>
  <operation>
    <authentication>
      <login>
        <userid>Admin</userid>
        <companyid>Seed_MCPMEGA_042516_may16</companyid>
        <password>REMOVED_FOR_SECURITY_PURPOSES</password>
      </login>
    </authentication>
    <content>
      <function controlid="testFunctionId">
        <get_list object="apterm" maxitems="10"></get_list>
      </function>
      <function controlid="testFunctionId">
        <get_list object="apterm" maxitems="10"></get_list>
      </function>
    </content>
  </operation>
  <operation>
    <authentication>
      <login>
        <userid>Admin</userid>
        <companyid>Seed_MCPMEGA_042516_may16</companyid>
        <password>REMOVED_FOR_SECURITY_PURPOSES</password>
      </login>
    </authentication>
    <content>
      <function controlid="testFunctionId">
        <get_list object="apterm" maxitems="10"></get_list>
      </function>
      <function controlid="testFunctionId">
        <get_list object="apterm" maxitems="10"></get_list>
      </function>
    </content>
  </operation>
</request>

No response.

**Comment by jimmymcpeter** [comment]
Suresh, can you give us more info?  The tool was never designed for multi operations so I'm not quite sure what you mean

**Comment by jimmymcpeter** [comment]
Multiple operations is not supported and we have no plans to support this.  We'd like to get rid of the ability to even pass multiple operations so allowing it in the tool will encourage bad behavior.
