### ISSUE TITLE
MIssing existing sample scripts based on DTD.

### ISSUE THREAD

**Issue by sshettyintacct** [Intacct/intacct-ws-test-tool#15]
Expecting all 3.0 API calls sample XML.
1. Inspect
2. Inspect Detail
3. Create
4. Update
5. Read
6. ReadByName
7. ReadByQuery
8. ReadMore
9. Delete
10. ReadReport
11. ReadView

Please provide a link to developer.intacct.com for more help.

Also 2.1 Sample call like get and get_list.

**Comment by jimmymcpeter** [comment]
Duplicate with issue #8
