### ISSUE TITLE
<docparid> should come only for SO, PO and INVDOCUMENT objects and only with readByQuery API

### ISSUE THREAD

**Issue by sshettyintacct** [Intacct/intacct-ws-test-tool#44]
<content>
  <function controlid="testFunctionId">
    <read>
      <object>GLBATCH</object>
      <keys></keys>
      <fields>*</fields>
      <returnFormat>xml</returnFormat>
      **<docparid></docparid>**
    </read>
  </function>
</content>

<content>
  <function controlid="testFunctionId">
    <readByQuery>
      <object>**GLBATCH**</object>
      <query></query>
      <fields>*</fields>
      <pagesize>100</pagesize>
      <returnFormat>xml</returnFormat>
      **<docparid></docparid>**
    </readByQuery>
  </function>
</content>

**Comment by jimmymcpeter** [comment]
<docparid> is an optional field defined by the schema.  It doesn't hurt for the null element to be there.
