### ISSUE TITLE
Provide "advanced" path to paste in XML request (supported in previous tool)

### ISSUE THREAD

**Issue by stopthepress** [Intacct/intacct-ws-test-tool#45]
The new tool is great for a beginning user and would've really helped me when I first started, good job!

In the prior tool, you can take a properly formatted request object and paste it into the bottom section and hit post (after supplying just the company id and intacct logon). I have several hundred saved xml requests. These no longer work when pasting into the bottom section of the tool. I have to  remove the operation, authentication, etc. to get them to work. Can you provide the prior "advanced" path?

**Comment by jimmymcpeter** [comment]
The purpose of the tool is to assist with generating the request itself, for testing.  If you're providing your own full XML requests, this makes the purpose of the tool a little moot.  Why not just use a tool like Postman then?  Providing an advanced path (while is an option we will take into consideration) encourages folks to hard code their passwords in files like you may have done.  We have taken a firm stance to NOT encourage this risky bad behavior.

**Comment by stopthepress** [comment]
I'm unfamiliar with those tools, but I will check them out, thanks. I've only used the prior API Test tool for these kinds of requests, just mentioning it because this behavior was supported in the prior version of the Test tool. I'm not saving credentials in the xml.
